// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL0JI0ArW7OTK5bQNHRDjGROunCif07Y4',
    appId: '1:401382704716:web:7ca9e29def900d017196e9',
    messagingSenderId: '401382704716',
    projectId: 'answer-messenger',
    authDomain: 'answer-messenger.firebaseapp.com',
    storageBucket: 'answer-messenger.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP1RRyYi2Euvm--8xF5cqgcV8Eora9XqI',
    appId: '1:401382704716:android:b3aa484f5cb3e0427196e9',
    messagingSenderId: '401382704716',
    projectId: 'answer-messenger',
    storageBucket: 'answer-messenger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI3XXr5mQ8EOusLkqDvonxGXQCBJmwXd0',
    appId: '1:401382704716:ios:d441cfaf4e521e547196e9',
    messagingSenderId: '401382704716',
    projectId: 'answer-messenger',
    storageBucket: 'answer-messenger.firebasestorage.app',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI3XXr5mQ8EOusLkqDvonxGXQCBJmwXd0',
    appId: '1:401382704716:ios:d441cfaf4e521e547196e9',
    messagingSenderId: '401382704716',
    projectId: 'answer-messenger',
    storageBucket: 'answer-messenger.firebasestorage.app',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL0JI0ArW7OTK5bQNHRDjGROunCif07Y4',
    appId: '1:401382704716:web:9a86745208ab5d7b7196e9',
    messagingSenderId: '401382704716',
    projectId: 'answer-messenger',
    authDomain: 'answer-messenger.firebaseapp.com',
    storageBucket: 'answer-messenger.firebasestorage.app',
  );
}
