// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3oa2a7CjeLl0yM3tmOCKR35bxGZE1K-0',
    appId: '1:577703671325:web:0d04d2563ede093fceb8f4',
    messagingSenderId: '577703671325',
    projectId: 'answer-application',
    authDomain: 'answer-application.firebaseapp.com',
    storageBucket: 'answer-application.firebasestorage.app',
    measurementId: 'G-1E8SFZCYCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmpuCBqEhqNeDaDxkFjS6AAeKqskx9krE',
    appId: '1:577703671325:android:aab85b3e02dc0e92ceb8f4',
    messagingSenderId: '577703671325',
    projectId: 'answer-application',
    storageBucket: 'answer-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzqgkx_5dW5pSA-K2kkrcybKSH5-l7R2E',
    appId: '1:577703671325:ios:1b66e0c656ccb764ceb8f4',
    messagingSenderId: '577703671325',
    projectId: 'answer-application',
    storageBucket: 'answer-application.firebasestorage.app',
    androidClientId: '577703671325-13b50n2rugna5i55det9csk7368mt27t.apps.googleusercontent.com',
    iosClientId: '577703671325-ti2i1ietksdh5pct64qg5d8cpe8v8ope.apps.googleusercontent.com',
    iosBundleId: 'com.answer.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzqgkx_5dW5pSA-K2kkrcybKSH5-l7R2E',
    appId: '1:577703671325:ios:9099e38cde2b0874ceb8f4',
    messagingSenderId: '577703671325',
    projectId: 'answer-application',
    storageBucket: 'answer-application.firebasestorage.app',
    androidClientId: '577703671325-13b50n2rugna5i55det9csk7368mt27t.apps.googleusercontent.com',
    iosClientId: '577703671325-smdroo0f1l6oln0chmae8j2ea0f7e8kh.apps.googleusercontent.com',
    iosBundleId: 'com.answer.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3oa2a7CjeLl0yM3tmOCKR35bxGZE1K-0',
    appId: '1:577703671325:web:0d04d2563ede093fceb8f4',
    messagingSenderId: '577703671325',
    projectId: 'answer-application',
    authDomain: 'answer-application.firebaseapp.com',
    storageBucket: 'answer-application.firebasestorage.app',
  );

}